// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADxQK8OdbIQwQ9AxWaIpvTcDwkHtiJGxM',
    appId: '1:619782197174:web:edc848e7b9bb45d947fb17',
    messagingSenderId: '619782197174',
    projectId: 'fitnessplanner-c89c1',
    authDomain: 'fitnessplanner-c89c1.firebaseapp.com',
    storageBucket: 'fitnessplanner-c89c1.firebasestorage.app',
    measurementId: 'G-8FYGLMH82M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEbDPMnnt4Yyi52G63RCymCzZBzW642qs',
    appId: '1:619782197174:android:a9a25ccfba59971a47fb17',
    messagingSenderId: '619782197174',
    projectId: 'fitnessplanner-c89c1',
    storageBucket: 'fitnessplanner-c89c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRES8tOVJCvTm5DcA4Ggl_H1zlm7u2x3Q',
    appId: '1:619782197174:ios:e2ec54c6ec81811047fb17',
    messagingSenderId: '619782197174',
    projectId: 'fitnessplanner-c89c1',
    storageBucket: 'fitnessplanner-c89c1.firebasestorage.app',
    iosBundleId: 'com.example.fitnessPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRES8tOVJCvTm5DcA4Ggl_H1zlm7u2x3Q',
    appId: '1:619782197174:ios:e2ec54c6ec81811047fb17',
    messagingSenderId: '619782197174',
    projectId: 'fitnessplanner-c89c1',
    storageBucket: 'fitnessplanner-c89c1.firebasestorage.app',
    iosBundleId: 'com.example.fitnessPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADxQK8OdbIQwQ9AxWaIpvTcDwkHtiJGxM',
    appId: '1:619782197174:web:80f883d632a8038d47fb17',
    messagingSenderId: '619782197174',
    projectId: 'fitnessplanner-c89c1',
    authDomain: 'fitnessplanner-c89c1.firebaseapp.com',
    storageBucket: 'fitnessplanner-c89c1.firebasestorage.app',
    measurementId: 'G-BLCZFV37WG',
  );
}
