// lib/main.dart
// App entry point — Firebase initialization + Provider setup + routing

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:provider/provider.dart';

import 'providers/app_provider.dart';
import 'utils/app_theme.dart';
import 'screens/auth/login_screen.dart';
import 'screens/auth/signup_screen.dart';
import 'screens/home/home_screen.dart';
import 'screens/workout/workout_list_screen.dart';
import 'screens/workout/create_routine_screen.dart';
import 'screens/workout/workout_detail_screen.dart';
import 'screens/exercise/exercise_library_screen.dart';
import 'screens/progress/progress_screen.dart';
import 'screens/profile/profile_screen.dart';
import 'screens/ai/ai_features_screen.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(
    ChangeNotifierProvider(
      create: (_) => AppProvider(),
      child: const FitAIApp(),
    ),
  );
}

class FitAIApp extends StatelessWidget {
  const FitAIApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'FitAI Planner',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.darkTheme,
      home: const _AuthGate(),
      routes: {
        '/login':          (_) => const LoginScreen(),
        '/signup':         (_) => const SignupScreen(),
        '/home':           (_) => const MainShell(),
        '/workouts':       (_) => const WorkoutListScreen(),
        '/create-routine': (_) => const CreateRoutineScreen(),
        '/exercises':      (_) => const ExerciseLibraryScreen(),
        '/progress':       (_) => const ProgressScreen(),
        '/profile':        (_) => const ProfileScreen(),
        '/ai':             (_) => const AiFeaturesScreen(),
      },
      onGenerateRoute: (settings) {
        if (settings.name == '/workout-detail') {
          return MaterialPageRoute(
            builder: (_) => WorkoutDetailScreen(
              routine: settings.arguments as dynamic,
            ),
          );
        }
        return null;
      },
    );
  }
}

// ─── AUTH GATE (StatefulWidget to avoid rebuild loop) ──────────────────────

class _AuthGate extends StatefulWidget {
  const _AuthGate();

  @override
  State<_AuthGate> createState() => _AuthGateState();
}

class _AuthGateState extends State<_AuthGate> {
  @override
  void initState() {
    super.initState();
    // Listen to Firebase auth state changes ONCE — update provider
    FirebaseAuth.instance.authStateChanges().listen((user) {
      if (mounted) {
        context.read<AppProvider>().setUser(user);
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Consumer<AppProvider>(
      builder: (context, provider, _) {
        // ── 1. First launch: waiting for Firebase to respond ──────────────
        // isInitializing is true ONLY until first authStateChanges fires.
        // Use this — NOT isLoading — so we never show splash after login.
        if (provider.isInitializing) {
          return const _SplashScreen();
        }

        // ── 2. Logged in ──────────────────────────────────────────────────
        if (provider.currentUser != null) {
          return const MainShell();
        }

        // ── 3. Not logged in ──────────────────────────────────────────────
        return const LoginScreen();
      },
    );
  }
}

// ─── SPLASH SCREEN ─────────────────────────────────────────────────────────

class _SplashScreen extends StatelessWidget {
  const _SplashScreen();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF0A0E1A),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Container(
              width: 80,
              height: 80,
              decoration: BoxDecoration(
                color: const Color(0xFF00E5A0).withOpacity(0.15),
                borderRadius: BorderRadius.circular(24),
              ),
              child: const Icon(
                Icons.fitness_center,
                color: Color(0xFF00E5A0),
                size: 40,
              ),
            ),
            const SizedBox(height: 20),
            const Text(
              'FitAI Planner',
              style: TextStyle(
                color: Colors.white,
                fontSize: 28,
                fontWeight: FontWeight.w700,
                letterSpacing: -0.5,
              ),
            ),
            const SizedBox(height: 8),
            const Text(
              'Loading...',
              style: TextStyle(color: Color(0xFF8A95AA), fontSize: 14),
            ),
            const SizedBox(height: 32),
            const CircularProgressIndicator(
              color: Color(0xFF00E5A0),
              strokeWidth: 2,
            ),
          ],
        ),
      ),
    );
  }
}

// ─── MAIN SHELL (Bottom Navigation) ────────────────────────────────────────

class MainShell extends StatefulWidget {
  const MainShell({super.key});

  @override
  State<MainShell> createState() => _MainShellState();
}

class _MainShellState extends State<MainShell> {
  int _selectedIndex = 0;

  // All main tabs
  final List<Widget> _pages = const [
    HomeScreen(),
    WorkoutListScreen(),
    ExerciseLibraryScreen(),
    ProgressScreen(),
    ProfileScreen(),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: IndexedStack(
        index: _selectedIndex,
        children: _pages,
      ),
      bottomNavigationBar: Container(
        decoration: const BoxDecoration(
          border: Border(
            top: BorderSide(color: Color(0xFF1E2840), width: 1),
          ),
        ),
        child: BottomNavigationBar(
          currentIndex: _selectedIndex,
          onTap: (index) => setState(() => _selectedIndex = index),
          items: const [
            BottomNavigationBarItem(
              icon: Icon(Icons.home_outlined),
              activeIcon: Icon(Icons.home),
              label: 'Home',
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.calendar_today_outlined),
              activeIcon: Icon(Icons.calendar_today),
              label: 'Workouts',
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.fitness_center_outlined),
              activeIcon: Icon(Icons.fitness_center),
              label: 'Exercises',
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.show_chart_outlined),
              activeIcon: Icon(Icons.show_chart),
              label: 'Progress',
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.person_outline),
              activeIcon: Icon(Icons.person),
              label: 'Profile',
            ),
          ],
        ),
      ),
    );
  }
}